version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable:
    - gofmt

linters-settings:
  errcheck:
    check-type-assertions: true

issues:
  exclude-use-default: true
